### ISSUE TITLE
Question on whether use A as 1 or 11 in blackjack

### ISSUE THREAD

**Issue by apple601601601** [Duane321/mutual_information#3]
Hi @Duane321,
First thanks for the fantastic videos and codes.

I've got a question in the [blackjack.py](https://github.com/Duane321/mutual_information/blob/main/videos/monte_carlo_for_RL_and_off_policy_methods/blackjack.py) for function calc_sum_useable_ace():
It seems the function always tries to use 'A' as 11 whenever possible.

However in real life scenarios once might want to use 'A' as 1 and potentially hit more card.
So is that because use 'A' as 11 always get you higher chance of winning or some other reasons?

Thanks

**Comment by Duane321** [comment]
Oh it's been awhile, but I think either..

1) It's known as part of the optimal strategy. There may be some mathematical fact about this blackjack game where it's never right to use an ace as a 1 when you can use it as an 11.
2) It's not known as a part of the optimal strategy, but the designers used it as an approximate assumption.

I forget which it is..

**Comment by apple601601601** [comment]
Thank you. Feels like #2. I will check more and get back if any findings.
